---
Name: website_parsing
After:
  - 'framework/*'
  - 'cms/*'
---
Injector:
  Fetcher:
    class: ContentsFetcher
  ImageFetcher:
    class: ImageFetcher
TumblrApi:
  Key: foobarbaz
SoundCloudApi:
  Key: foobarbaz
ImageFetcher:
  Folder: websites